(()=>{
 const form=document.getElementById('solution-form');if(!form)return;form.hidden=false;
 const suggestions={
  'Data centre & servers':['Design a new server room or data centre','Upgrade servers, storage or backup','Plan disaster recovery'],
  'Cloud & migration':['Move email and files to Microsoft 365','Migrate workloads to the cloud','Review cloud backup and running costs'],
  'Networking & Wi-Fi':['Improve office Wi-Fi coverage','Connect multiple locations','Install or upgrade structured cabling'],
  'Cybersecurity & CCTV':['Review network and endpoint security','Install CCTV or access control','Improve firewall protection'],
  'Software & business apps':['Build a website or customer portal','Develop a custom business application','Automate a manual business process'],
  'Devices & IT support':['Supply or upgrade business devices','Arrange ongoing IT support','Repair or maintain existing equipment'],
  'Power & cooling':['Plan UPS and power protection','Improve server-room cooling','Review power and cooling capacity'],
  'Help me decide':['Assess our current IT setup','Discuss business goals with a consultant']
 };
 let step=0;let summary='';const selectedSuggestions=new Set();
 const needs=()=>Array.from(form.querySelectorAll('[name=needs]:checked'),x=>x.value);
 const description=form.elements.description;
 const status=document.getElementById('solution-status');
 function updateSuggestions(){const chosen=needs();const opts=[...new Set(chosen.flatMap(n=>suggestions[n]||[]))];for(const v of selectedSuggestions)if(!opts.includes(v))selectedSuggestions.delete(v);const parent=document.getElementById('suggestion-options');parent.replaceChildren();opts.forEach(value=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.name='suggestions';input.value=value;input.checked=selectedSuggestions.has(value);input.addEventListener('change',()=>input.checked?selectedSuggestions.add(value):selectedSuggestions.delete(value));const text=document.createElement('span');text.textContent=value;label.append(input,text);parent.append(label)});document.getElementById('solution-suggestions').hidden=!opts.length;description.required=chosen.includes('Something else');document.getElementById('description-required').textContent=description.required?'(required)':'(optional)';document.getElementById('needs-error').hidden=chosen.length>0;}
 form.querySelectorAll('[name=needs]').forEach(e=>e.addEventListener('change',updateSuggestions));
 function validate(){if(step===1&&window.solutionPhone&&!window.solutionPhone.validate()){form.elements.phone.reportValidity();return false;}if(step===0&&!needs().length){document.getElementById('needs-error').hidden=false;form.querySelector('[name=needs]').focus();return false;}const controls=form.querySelectorAll('[data-step="'+step+'"] input,[data-step="'+step+'"] textarea,[data-step="'+step+'"] select');for(const input of controls){if(input.required&&input.value.trim()==='')input.setCustomValidity('Please complete this field.');else input.setCustomValidity('');if(!input.reportValidity())return false;}return true;}
 form.addEventListener('input',e=>{if(e.target.setCustomValidity)e.target.setCustomValidity('');});
 function buildSummary(){const value=name=>form.elements[name].value.trim();summary=['CAPITAL GROUP — SOLUTION ENQUIRY','', 'Name: '+value('clientName'),'Organisation: '+(value('company')||'Not provided'),'Email: '+(value('email')||'Not provided'),'Phone: '+(window.solutionPhone?window.solutionPhone.number():value('phone')),'','Services of interest:',...needs().map(n=>'• '+n),'',...(selectedSuggestions.size?['Possible starting points:',...Array.from(selectedSuggestions,s=>'• '+s),'']:[]),'What I would like to achieve:',value('description')||'I would like guidance on the best approach.','','People / devices: '+value('size'),'Preferred start: '+value('timing'),'Project location: '+(value('location')||'To discuss'),'Budget: '+(value('budget')||'To discuss')].join('\n');document.getElementById('solution-summary').textContent=summary;document.getElementById('send-whatsapp').href='https://wa.me/233246403570?text='+encodeURIComponent(summary);document.getElementById('send-email').href='mailto:wisdom.adjah@capitalgroupls.com?cc=manassehafenyah%40gmail.com&subject='+encodeURIComponent('Capital Group solution enquiry — '+value('clientName'))+'&body='+encodeURIComponent(summary);status.textContent='';}
 function show(n){step=n;if(n===2)buildSummary();form.querySelectorAll('[data-step]').forEach(el=>el.hidden=Number(el.dataset.step)!==n);document.querySelectorAll('[data-progress]').forEach(el=>{if(Number(el.dataset.progress)===n)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});const target=form.querySelector('[data-step="'+n+'"]');const heading=target.querySelector('h3,legend');heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:'auto'});}
 form.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>{if(validate())show(Number(b.dataset.next));}));form.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.back))));
 form.addEventListener('submit',e=>{e.preventDefault();if(step<2&&validate())show(step+1);});
 form.querySelector('.copy-brief').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(summary);status.textContent='Brief copied. You can paste it into a message or email.';}catch{status.textContent='Select and copy the brief above to paste it into your message.';}});
})();
